### ISSUE TITLE
Unable to verify mailbox after registration

### ISSUE THREAD

**Issue by yangminglong** [husarnet/husarnet#64]
I have receive two email,
Topic1:Activate Your Husarnet Account
Topic2:Welcome To Husarnet! Start Your Journey With Low Latency Connectivity
In these two emails, I can't find the link to verify my email .
I click the logo in the email, and I will enter husarnet.com, which will lead to account confirmation. I click "reset confirmation mail" and can't receive any new mail

**Comment by yangminglong** [comment]
Activate Your Husarnet Account
Husarnet
发给 yml0305@live.com
隐藏信息2022-07-19 11:47
发件人: 
Husarnet<contact@husarnet.com>
收件人: 
yml0305@live.com<yml0305@live.com>
时间: 
2022年7月19日 (周二) 11:47
大小: 
144 KB

LOGO
No longer want to receive these emails? [Unsubscribe]...

**Comment by KonradPR** [comment]
Hi,
sorry for taking a long time to reply, but we have thoroughly investigated the problem You have reported. 
We decided that the best course of action would be for us to manually activate Your profile.
Your account should now be active and You should be able to use it without further problems.
Please confirm that he issue has been resolved so that I can close this discussion.

Best regards,
Konrad

**Comment by yangminglong** [comment]
> Hi, sorry for taking a long time to reply, but we have thoroughly investigated the problem You have reported. We decided that the best course of action would be for us to manually activate Your profile. Your account should now be active and You should be able to use it without further problems. Please confirm that he issue has been resolved so that I can close this discussion.
> 
> Best regards, Konrad

Hi, Thank you for your reply.

My problem still exists.

On July 20, I received an email with the following content:
Topic:    Create A Network And Connect Your Devices
content:You can log into your Husarnet account by clicking **here**.

I clicked **here**. 

From the day forth, I Click the "login" button from the web page:
https://app.husarnet.com/accounts/login/?     then i will enter the web page:
https://app.husarnet.com/accounts/profile/    which the web page content  is:

**Not Found**
The requested resource was not found on this server.

**Comment by yangminglong** [comment]
> > Hi, sorry for taking a long time to reply, but we have thoroughly investigated the problem You have reported. We decided that the best course of action would be for us to manually activate Your profile. Your account should now be active and You should be able to use it without further problems. Please confirm that he issue has been resolved so that I can close this discussion.
> > Best regards, Konrad
> 
> Hi, Thank you for your reply.
> 
> My problem still exists.
> 
> On July 20, I received an email with the following content: Topic: Create A Network And Connect Your Devices content:You can log into your Husarnet account by clicking **here**.
> 
> I clicked **here**.
> 
> From the day forth, I Click the "login" button from the web page: https://app.husarnet.com/accounts/login/? then i will enter the web page: https://app.husarnet.com/accounts/profile/ which the web page content is:
> 
> **Not Found** The requested resource was not found on this server.

My problem should be solved

Although I will enter after logging in https://app.husarnet.com/accounts/profile/ "Not found" will be prompted

But I tried to enter https://app.husarnet.com/ After that, I can enter the "account settings" page

**Comment by KonradPR** [comment]
Thank You for further reply.
It seems that You have been hitting a non-existing path /accounts/profile/. 
Our theory is that You landed there due to an error in our redirecting policies since while trying to access /accounts/profile/ You should be redirected to a proper path. We assume that his is a small bug on our side and will investigate further in order to identify the underlying source of the problem. Thank You for You submission we have now added solving the bug to our internal roadmap and will try to fix it in the near future so that no further instances of the problem occur.

As of now I am closing this issue since the problem should not occur frequently and should be solved in a reasonable amount of time.

Best regards,
Konrad
